version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: fugo_db
    environment:
      POSTGRES_USER: fugo
      POSTGRES_PASSWORD: fugopass
      POSTGRES_DB: fugo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
        - "9000:9000"
        - "9090:9090"
    command:
    - server
    - /data
    - --console-address
    - ":9090"
    volumes:
      - ./minio-init.sh:/minio-init.sh
      - minio_data:/data
    entrypoint: >
      /bin/sh -c "
      /usr/bin/docker-entrypoint.sh server /data --console-address ':9090' &
      sleep 10 &&
      /usr/bin/mc alias set local http://localhost:9000 minioadmin minioadmin &&
      /usr/bin/mc mb local/images --ignore-existing &&
      /usr/bin/mc anonymous set download local/images &&
      wait
      "

volumes:
  postgres_data:
  minio_data: 