export enum HealthStatusEnum {
	EXCELLENT = "EXCELLENT",
	GOOD = "GOOD",
	AVERAGE = "AVERAGE",
	TIRED = "TIRED",
	INJURED = "INJURED",
	SICK = "SICK",
	RECOVERING = "RECOVERING",
	EXHAUSTED = "EXHAUSTED",
}
