export enum SpotDangersEnum {
	STRONG_CURRENTS = "STRONG_CURRENTS",
	HIGH_WAVES = "HIGH_WAVES",
	LOW_VISIBILITY = "LOW_VISIBILITY",
	EXTREME_TEMPERATURE = "EXTREME_TEMPERATURE",
	DEEP_WATER = "DEEP_WATER",
	SHARP_ROCKS_CORALS = "SHARP_ROCKS_CORALS",
	CAVES_AND_BLUE_HOLES = "CAVES_AND_BLUE_HOLES",
	VENOMOUS_FISH = "VENOMOUS_FISH",
	SHARKS = "SHARKS",
	BOAT_TRAFFIC = "BOAT_TRAFFIC",
	ACCESSIBILITY = "ACCESSIBILITY",
}
