export enum WaterEquipmentEnum {
	MASK = "MASK",
	SNORKEL = "SNORKEL",
	FINS = "FINS",
	WETSUIT = "WETSUIT",
	DIVE_LIGHTS = "DIVE_LIGHTS",
	DIVING_BOOTS = "DIVING_BOOTS",
	DIVING_GLOVES = "DIVING_GLOVES",
	FLASHLIGHT = "FLASHLIGHT",
	WEIGHT_BELT = "WEIGHT_BELT",
}
